# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recognizer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recognizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import stt_pb2 as stt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10recognizer.proto\x12\x10speechkit.stt.v3\x1a\tstt.proto2o\n\nRecognizer\x12\x61\n\x12RecognizeStreaming\x12\".speechkit.stt.v3.StreamingRequest\x1a#.speechkit.stt.v3.StreamingResponse(\x01\x30\x01\x42\x12Z\x10local/stt/v3;sttb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020local/stt/v3;stt'
  _globals['_RECOGNIZER']._serialized_start=49
  _globals['_RECOGNIZER']._serialized_end=160
# @@protoc_insertion_point(module_scope)
